$schema: "https://json-schema.org/draft/2020-12/schema"
title: cfClone Pipeline Schema
description: Snakemake configuration file for cfClone pipeline
type: object
properties:
  out_dir:
    type: string
    minLength: 1
    description: Path to output directory
  pipeline_dir:
    type: string
    minLength: 1
    description: Path to pipeline working directory

  clonal_cn_file:
    type: string
    minLength: 1
    description: Path to input clonal copy-number profiles
  clone_tree_newick:
    type: string
    minLength: 1
    description: Path to input clonal copy-number tree, in newick (.nwk) format
  ctdna_file:
    type: string
    minProperties: 1
    description: Path to input ctDNA file

  num_chains:
    type: integer
    minimum: 1
    default: 16
  num_chains_vi:
    type: integer
    minimum: 1
    default: 8
  num_rounds:
    type: integer
    minimum: 1
    default: 10
  num_threads:
    type: integer
    minimum: 1
    default: 10
